[package]
name = "quaturn"
version = "0.1.3"
edition = "2024"
repository = "https://github.com/ToothlessBrush/Quaturn"
description = "A 3D game engine written in Rust"
license = "MIT"
authors = ["ToothlessBrush <johnklein514@gmail.com."]
readme = "README.md"
keywords = ["3d", "game", "engine", "gamedev", "graphics"]
categories = ["game-engines", "graphics"]

include = [
    "res/primitives/**/*",
    "res/shaders/**/*",
    "**/*.rs",
    "cargo.toml"
]

exclude = [
    "res/models/**/*"
]

[lib]
name = "quaturn"
path = "src/lib.rs"

[dependencies]
colored = "2.1.0"
dyn-clone = "1.0.17"
egui_gl_glfw = "0.1.9"
gl = "0.14.0"
gltf = { version = "1.4.1", features = ["KHR_materials_pbrSpecularGlossiness"] }
image = "0.25.6"
nalgebra-glm = "0.18.0"
stb_image = "0.3.0"

