[package]
name = "maple_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
winit = "0.30.12"
maple_renderer = {path = "../maple_renderer", version = "0.1.0"}
bitflags = "2.9.1"
bytemuck = "1.23.2"
