[book]
title = "Maple Game Engine Guide"
authors = ["ToothlessBrush"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/ToothlessBrush/maple"
edit-url-template = "https://github.com/ToothlessBrush/maple/edit/main/guide/{path}"
